[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/go-spatial/tegola"
  branch = "jivan"
  source = "github.com/ingenieroariel/tegola"

[[constraint]]
  name = "github.com/go-spatial/geom"
  branch = "jivan"
  source = "github.com/ingenieroariel/geom"

[[constraint]]
  revision = "b743c9cc2841b94d9db3d4628abd6ee0b684d1f4"
  name = "github.com/getkin/kin-openapi"

[[constraint]]
  branch = "master"
  name = "github.com/julienschmidt/httprouter"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/xeipuuv/gojsonschema"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/akrylysov/algnhsa"
  version = "0.5.0"
